spring.application.name=project

# Ã¬ÂÂÃ«Â²Â Ã­ÂÂ¬Ã­ÂÂ¸Ã«Â²ÂÃ­ÂÂ¸ Ã¬ÂÂ¤Ã¬Â Â
server.port=9005

# Log level Ã¬ÂÂ¤Ã¬Â Â
logging.level.root=info

# DB (MySQL) Ã¬ÂÂ°Ã«ÂÂ Ã¬ÂÂ¤Ã¬Â Â
spring.datasource.url=jdbc:mysql://localhost:3306/project
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=root

# Ã«Â¡ÂÃªÂ·Â¸Ã¬ÂÂ Ã¬Â¶ÂÃ«Â Â¥Ã«ÂÂÃ«ÂÂ Ã¬Â¿Â¼Ã«Â¦Â¬ Ã­ÂÂ¬Ã«Â©ÂÃ­ÂÂ
# JPAÃ¬ÂÂ ÃªÂµÂ¬Ã­ÂÂÃ¬Â²Â´Ã¬ÂÂ¸ HibernateÃªÂ°Â Ã«ÂÂÃ¬ÂÂÃ­ÂÂÃ«Â©Â´Ã¬ÂÂ Ã«Â°ÂÃ¬ÂÂÃ­ÂÂ SQLÃ¬ÂÂ ÃªÂ°ÂÃ«ÂÂÃ¬ÂÂ±Ã¬ÂÂ Ã«ÂÂÃ¬ÂÂ¬Ã¬Â¤Â
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# HikariCP (ÃªÂ¸Â°Ã«Â³Â¸ Ã¬Â»Â¤Ã«ÂÂ¥Ã¬ÂÂ Ã­ÂÂ) Ã¬ÂÂ¤Ã¬Â Â
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.minimum-idle=10
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=1800000

# 캐시 설정 여부 false
spring.thymeleaf.cache=false

# 업로드 용량 설정(default : 1M)
# 파일 업로드를 위한 설정
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB


# 파일 저장 위치 설정 (윈도우)
spring.servlet.multipart.location=c:/uploadPath

openai.api.key=ENC(Vp56OygDF1RxV5R2bdfxKwp9c7OqCJdEoP5HjiU/9xBBjm929a6t3S1Wk9v1CGhKrBTuRjRra1F1Hu1eQL2BPWEeXrhXr5JmQpG+mRKtRMzBFcVblnMxGYkSRAV3WWMmgF9nWorXhzSNEd5nBp/GV6Axx4438MyigJHHd37npDuphcBRw5c8CCyGeJNwZ1LUxboeiiTBmR/FogsTKnbE+jQsVl6u4Zhx6QQyIyqmleg=)
openai.api.model=gpt-3.5-turbo
openai.api.temperature=0.7

# Redis 및 Email 설정
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sjpublicgpt@gmail.com
spring.mail.password=ENC(5HHBn6df+itNIxEOHhnYh57o33C2ogym2nn2+1T2IK4=)

spring.mail.default-encoding=UTF-8

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

mail.sender.email=sjpublicgpt@gmail.com
jasypt.encryptor.bean=JasyptEncoder