spring.application.name=project

# 서버 포트번호 설정
server.port=9005

# Log level 설정
logging.level.root=info

# DB (MySQL) 연동 설정
spring.datasource.url=jdbc:mysql://localhost:3306/project
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=root

# 로그에 출력되는 쿼리 포메팅
# JPA의 구현체인 Hibernate가 동작하면서 발생한 SQL의 가독성을 높여줌
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# HikariCP (기본 커넥션 풀) 설정
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.minimum-idle=10
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=1800000
openai.api.key=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
# 캐시 설정 여부 false
spring.thymeleaf.cache=false