spring.application.name=project

server.port=9005

logging.level.root=info

spring.datasource.url=ENC(jdsThSiGwrCWYcgYD/qlooB40zNi//T+IeacH2nEwysN4qChBUDMuAcsUy3Qmll2)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=ENC(i/9VT2ZrmFqqotzy1LrS4A==)
spring.datasource.password=ENC(/JuDCmH7vOD2Q/ZILhQYJg==)
jasypt.encryptor.iv-generator-classname=org.jasypt.iv.NoIvGenerator

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.jdbc.batch_size = 50
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.minimum-idle=10
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=1800000

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB


spring.servlet.multipart.location=/home/ubuntu/uploadPath

openai.api.key=ENC(MkEwberxSdbGcAIUw3CE9UksMORSVChW9Juu7D1BXYLdPUJkwqLU3RlOYZG8hyFnF9hZP26rHs2bI2L+WRlr470ZnBoEDgyjLxGFS0hdZRSB8wLWbXX+xjkXr3EJ9Wr0tcKa6p5lsoMiAoxXBWIrRIUhoZ0kut8TLsTKL6ZTOtnQPMZ3SzybbiXmHVOeQ+HNBSTPb/6tbe92kyAu3f0TXy6tLKQOA41jGZJlSIDTjxY=)
openai.api.model=gpt-3.5-turbo
openai.api.temperature=0.7

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sjpublicgpt@gmail.com
spring.mail.password=ENC(qQJWIVv8/0L9tF7qQmHkNhdtWYiXplU5Rp4HFocCf5s=)

spring.mail.default-encoding=UTF-8

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

mail.sender.email=sjpublicgpt@gmail.com
jasypt.encryptor.bean=JasyptEncoder